name: fraud-detection-system
services:
- name: web
  source_dir: /
  github:
    repo: your-username/thisis_project
    branch: main
  run_command: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn myproject.wsgi:application
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: DJANGO_SETTINGS_MODULE
    value: myproject.settings_production
  - key: SECRET_KEY
    value: your-secret-key-here
  - key: ALLOWED_HOST
    value: fraud-detection-system.onrender.com
  # NO DATABASE ENVIRONMENT VARIABLES NEEDED - SQLite is included!

# NO DATABASES SECTION NEEDED - SQLite is included with your app!
