services:
  # Django web service
  - type: web
    name: fraud-detection-system
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: fraud-detection-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com

  # PostgreSQL database
  - type: pserv
    name: fraud-detection-db
    env: postgresql
    plan: free
    ipAllowList: []

