services:
  # Django web service
  - type: web
    name: fraud-detection-system
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python manage.py loaddata data_backup.json || echo "Data import failed, continuing with fresh database"
    startCommand: gunicorn myproject.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: fraud-detection-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PORT
        value: "10000"
    healthCheckPath: /

  # PostgreSQL database
  - type: pserv
    name: fraud-detection-db
    env: postgresql
    plan: free
    ipAllowList: []

