# Generated by Django 5.2.4 on 2025-08-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_systemsettings_alter_prediction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_level',
            field=models.CharField(choices=[('basic', 'Basic User'), ('admin', 'Administrator')], default='basic', max_length=10),
        ),
    ]
